services:
  - type: web
    name: rails-api-template
    region: ohio
    env: ruby
    plan: standard
    buildCommand: "bundle install && ./bin/rails assets:precompile"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "./bin/rails server"
    envVars:
      - fromGroup: rails-api-template-production
      - key: COOKIE_DOMAIN
        value: .example.com
      - key: DATABASE_URL
        fromDatabase:
          name: rails-api-template-production
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: /up
    autoDeploy: true
    
  - type: worker
    name: rails-api-template-worker
    region: ohio
    env: ruby
    plan: starter
    buildCommand: "bundle install"
    startCommand: "./bin/jobs start"
    envVars:
      - fromGroup: rails-api-template-production
      - key: DATABASE_URL
        fromDatabase:
          name: rails-api-template-production
          property: connectionString
    autoDeploy: true

databases:
  - name: rails-api-template-production
    region: ohio
    plan: pro-4gb
    user: rails_api_template_user