development:
  send_morning_notifications:
    class: SendMorningNotificationsJob
    queue: default
    schedule: every hour
  send_midday_notifications:
    class: SendMiddayNotificationsJob
    queue: default
    schedule: every hour
  send_afternoon_notifications:
    class: SendAfternoonNotificationsJob
    queue: default
    schedule: every hour
  send_evening_notifications:
    class: SendEveningNotificationsJob
    queue: default
    schedule: every hour
  send_wind_down_notifications:
    class: SendWindDownNotificationsJob
    queue: default
    schedule: every hour

production:
  # periodic_cleanup:
  #   class: CleanSoftDeletedRecordsJob
  #   queue: background
  #   args: [ 1000, { batch_size: 500 } ]
  #   schedule: every hour
  # periodic_command:
  #   command: "SoftDeletedRecord.due.delete_all"
  #   priority: 2
  #   schedule: at 5am every day
  send_morning_notifications:
    class: SendMorningNotificationsJob
    queue: default
    schedule: every hour
  send_midday_notifications:
    class: SendMiddayNotificationsJob
    queue: default
    schedule: every hour
  send_afternoon_notifications:
    class: SendAfternoonNotificationsJob
    queue: default
    schedule: every hour
  send_evening_notifications:
    class: SendEveningNotificationsJob
    queue: default
    schedule: every hour
  send_wind_down_notifications:
    class: SendWindDownNotificationsJob
    queue: default
    schedule: every hour
